/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DA.View;

/**
 *
 * @author admin
 */
public class KhachHang extends javax.swing.JPanel {

    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_timKiemKhachHang = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachHang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_diaChi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_maKhachHang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        btn_xoaKhachHang = new javax.swing.JButton();
        btn_themKhachHang = new javax.swing.JButton();
        txt_soDienThoai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã khách hàng:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 40));
        jPanel1.add(txt_timKiemKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 460, 40));

        btn_timKiem.setText("Tìm kiếm");
        jPanel1.add(btn_timKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        tbl_khachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã KH", "Tên", "SĐT", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(tbl_khachHang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 670, 400));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Địa chỉ:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, 30));
        jPanel3.add(txt_diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, 30));

        jLabel4.setText("Mã KH:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 40, 30));
        jPanel3.add(txt_maKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        jLabel5.setText("Tên:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 30));
        jPanel3.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, 30));

        btn_xoaKhachHang.setText("Xóa");
        jPanel3.add(btn_xoaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        btn_themKhachHang.setText("Thêm");
        jPanel3.add(btn_themKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel3.add(txt_soDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, 30));

        jLabel6.setText("SĐT:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 280, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Chi tiết khách hàng: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themKhachHang;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoaKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_khachHang;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_maKhachHang;
    private javax.swing.JTextField txt_soDienThoai;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timKiemKhachHang;
    // End of variables declaration//GEN-END:variables
}
