/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DA.View;
import DA.Unti.KhachHangModel;
import DA.Unti.KhachHangDAO;
import java.util.List;                 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class KhachHang extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyKhachHang
     */
    public KhachHang() {
        initComponents();
        loadTable();
    }
    
    private void loadTable() {
    KhachHangDAO dao = new KhachHangDAO();
    List<KhachHangModel> list = dao.getAll();

        DefaultTableModel model = (DefaultTableModel) tbl_khachHang.getModel();
    model.setRowCount(0);

    for (KhachHangModel kh : list) {
    model.addRow(new Object[]{
        kh.getMaKhachHang(),
        kh.getTen(),
        kh.getSdt(),
        kh.isGioiTinh() ? "Nam" : "Nữ",
        kh.getEmail()
    });
}
    System.out.println("Số lượng KH lấy được từ DB = " + list.size());


}
    
    private KhachHangDAO khachHangDAO = new KhachHangDAO();
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_timKiemKhachHang = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachHang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_maKhachHang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        btn_xoaKhachHang = new javax.swing.JButton();
        btn_themKhachHang = new javax.swing.JButton();
        txt_soDienThoai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã khách hàng:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 40));
        jPanel1.add(txt_timKiemKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 460, 40));

        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        tbl_khachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "SĐT", "Giới tính", "Email"
            }
        ));
        tbl_khachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachHang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 670, 400));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Giới tính:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, 30));
        jPanel3.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, 30));

        jLabel4.setText("Mã KH:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 40, 30));
        jPanel3.add(txt_maKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        jLabel5.setText("Tên:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 30));
        jPanel3.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, 30));

        btn_xoaKhachHang.setText("Xóa");
        btn_xoaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaKhachHangActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        btn_themKhachHang.setText("Thêm");
        btn_themKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themKhachHangActionPerformed(evt);
            }
        });
        jPanel3.add(btn_themKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel3.add(txt_soDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, 30));

        jLabel6.setText("SĐT:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 30));

        jLabel7.setText("Email:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, 30));

        jRadioButton1.setText("Nữ");
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jRadioButton2.setText("Nam");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 280, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Chi tiết khách hàng: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btn_themKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themKhachHangActionPerformed
        // TODO add your handling code here:
        KhachHangModel kh = new KhachHangModel();
    kh.setMaKhachHang(txt_maKhachHang.getText());
    kh.setTen(txt_ten.getText());
    kh.setSdt(txt_soDienThoai.getText());
    kh.setGioiTinh(jRadioButton2.isSelected()); 
    kh.setEmail(txt_email.getText());

    if (khachHangDAO.insert(kh)) {
        loadTable(); 
        javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Thêm thất bại!");
    }

    }//GEN-LAST:event_btn_themKhachHangActionPerformed

    private void btn_xoaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaKhachHangActionPerformed
        // TODO add your handling code here:
        int row = tbl_khachHang.getSelectedRow();
    if (row >= 0) {
        String maKH = tbl_khachHang.getValueAt(row, 0).toString();
        if (khachHangDAO.delete(maKH)) {
            loadTable();
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng để xóa");
    }

    }//GEN-LAST:event_btn_xoaKhachHangActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
         String keyword = txt_timKiemKhachHang.getText();
    List<KhachHangModel> list = khachHangDAO.search(keyword);
    DefaultTableModel model = (DefaultTableModel) tbl_khachHang.getModel();
    model.setRowCount(0);

    for (KhachHangModel kh : list) {
        model.addRow(new Object[]{
            kh.getMaKhachHang(),
            kh.getTen(),
            kh.getSdt(),
            kh.isGioiTinh() ? "Nam" : "Nữ",
            kh.getEmail()
        });
    }

    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void tbl_khachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachHangMouseClicked
        // TODO add your handling code here:
        int row = tbl_khachHang.getSelectedRow();
    if (row >= 0) {
        txt_maKhachHang.setText(tbl_khachHang.getValueAt(row, 0).toString());
        txt_ten.setText(tbl_khachHang.getValueAt(row, 1).toString());
        txt_soDienThoai.setText(tbl_khachHang.getValueAt(row, 2).toString());
        boolean gt = tbl_khachHang.getValueAt(row, 3).toString().equals("Nam");
        jRadioButton2.setSelected(gt);
        jRadioButton1.setSelected(!gt);
        txt_email.setText(tbl_khachHang.getValueAt(row, 4).toString());
    }

    }//GEN-LAST:event_tbl_khachHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themKhachHang;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoaKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_khachHang;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_maKhachHang;
    private javax.swing.JTextField txt_soDienThoai;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timKiemKhachHang;
    // End of variables declaration//GEN-END:variables
}
