/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DA.View;

import java.awt.CardLayout;

/**
 *
 * @author admin
 */
public class TrangChu extends javax.swing.JFrame {

    CardLayout cardLayout;
    
    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        cardLayout =(CardLayout) View.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        btn_viewSanPham = new javax.swing.JButton();
        btn_ViewHoaDon = new javax.swing.JButton();
        btn_ViewNhanVien = new javax.swing.JButton();
        btn_ViewKhachHang = new javax.swing.JButton();
        btn_ViewVocher = new javax.swing.JButton();
        btn_ViewThongKe = new javax.swing.JButton();
        View = new javax.swing.JPanel();
        hoaDon1 = new DA.View.HoaDon();
        sanPham1 = new DA.View.SanPham();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Home.setBackground(new java.awt.Color(51, 255, 255));

        btn_viewSanPham.setText("Sản Phẩm");
        btn_viewSanPham.setBorderPainted(false);
        btn_viewSanPham.setContentAreaFilled(false);
        btn_viewSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewSanPhamActionPerformed(evt);
            }
        });

        btn_ViewHoaDon.setText("Hóa Đơn");
        btn_ViewHoaDon.setBorderPainted(false);
        btn_ViewHoaDon.setContentAreaFilled(false);
        btn_ViewHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewHoaDonActionPerformed(evt);
            }
        });

        btn_ViewNhanVien.setText("Nhân Viên");
        btn_ViewNhanVien.setBorderPainted(false);
        btn_ViewNhanVien.setContentAreaFilled(false);
        btn_ViewNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewNhanVienActionPerformed(evt);
            }
        });

        btn_ViewKhachHang.setText("Khách Hàng");
        btn_ViewKhachHang.setBorderPainted(false);
        btn_ViewKhachHang.setContentAreaFilled(false);
        btn_ViewKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewKhachHangActionPerformed(evt);
            }
        });

        btn_ViewVocher.setText("Vocher");
        btn_ViewVocher.setBorderPainted(false);
        btn_ViewVocher.setContentAreaFilled(false);
        btn_ViewVocher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewVocherActionPerformed(evt);
            }
        });

        btn_ViewThongKe.setText("Thống Kê");
        btn_ViewThongKe.setBorderPainted(false);
        btn_ViewThongKe.setContentAreaFilled(false);
        btn_ViewThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ViewNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ViewKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(btn_ViewVocher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ViewThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_viewSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(btn_ViewHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btn_viewSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_ViewHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_ViewNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_ViewKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_ViewVocher, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_ViewThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        View.setLayout(new java.awt.CardLayout());
        View.add(hoaDon1, "HoaDon");
        View.add(sanPham1, "SanPham");

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 595, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewSanPhamActionPerformed
        // TODO add your handling code here:
        cardLayout.show(View,"SanPham");
    }//GEN-LAST:event_btn_viewSanPhamActionPerformed

    private void btn_ViewHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewHoaDonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(View,"HoaDon");
    }//GEN-LAST:event_btn_ViewHoaDonActionPerformed

    private void btn_ViewNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ViewNhanVienActionPerformed

    private void btn_ViewKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ViewKhachHangActionPerformed

    private void btn_ViewVocherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewVocherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ViewVocherActionPerformed

    private void btn_ViewThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ViewThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel View;
    private javax.swing.JButton btn_ViewHoaDon;
    private javax.swing.JButton btn_ViewKhachHang;
    private javax.swing.JButton btn_ViewNhanVien;
    private javax.swing.JButton btn_ViewThongKe;
    private javax.swing.JButton btn_ViewVocher;
    private javax.swing.JButton btn_viewSanPham;
    private DA.View.HoaDon hoaDon1;
    private javax.swing.JPanel jPanel1;
    private DA.View.SanPham sanPham1;
    // End of variables declaration//GEN-END:variables
}
